version: '{branch}-{build}'

# Do not build on tags (GitHub only)
skip_tags: true

image: Visual Studio 2022

branches:
  except:  # blacklist
    - coverity_scan

environment:
  nodejs_version: "16"
  REPO_DIR: &REPO_DIR c:\hestia

# project directory
clone_folder: *REPO_DIR

clone_depth: 50

install:
  - cd "%REPO_DIR%"
  - ps: Install-Product node $env:nodejs_version
  - npm install pnpm -g
  - pnpm i

build_script:
  - cd "%REPO_DIR%"
  - pnpm dist:win-np

after_build:
  - cd "%REPO_DIR%\release"
  - MKDIR upload
  - ls -a
  - COPY Hestia-v3.3.0-win-ia32.zip upload
  - COPY Hestia-v3.3.0-win-x64.zip upload
  - COPY Hestia_3.3.0.exe upload
  - COPY Hestia_3.3.0.exe.blockmap upload
  - COPY builder-debug.yml upload

test: off

artifacts:
  - path: \release\upload
    name: toshiki-hestia-appveyor-windows-x64
